software-mansion/starknet-jvm

.gitignore
android/build.gradle
androiddemo/build.gradle.kts
build.gradle.kts
lib/build.gradle.kts
lib/src/main/kotlin/starknet/data/types/responses.kt
lib/src/main/kotlin/starknet/data/types/transactions.kt
lib/src/main/kotlin/starknet/provider/Provider.kt
lib/src/main/kotlin/starknet/provider/gateway/GatewayProvider.kt
lib/src/main/kotlin/starknet/provider/rpc/JsonRpcProvider.kt

Also closes https://github.com/software-mansion/starknet.kt/issues/15

Fix android build

---

lib/src/main/kotlin/starknet/provider/gateway/GatewayProvider.kt

Adds factory methods to the gateway provider.

Add gateway provider factory

---

lib/src/test/kotlin/starknet/utils/DevnetClient.kt

Destroy devnet client process

---

lib/src/main/kotlin/starknet/data/nets.kt
lib/src/main/kotlin/starknet/data/responses/Transaction.kt
lib/src/main/kotlin/starknet/data/responses/TransactionReceipt.kt
lib/src/main/kotlin/starknet/data/responses/serializers/GatewayTransactionTransformingSerializer.kt
lib/src/main/kotlin/starknet/data/responses/serializers/JsonRpcTransactionPolymorphicSerializer.kt
lib/src/main/kotlin/starknet/data/types/execution.kt
lib/src/main/kotlin/starknet/provider/Provider.kt
lib/src/main/kotlin/starknet/provider/gateway/GatewayProvider.kt
lib/src/main/kotlin/starknet/provider/rpc/JsonRpcMethod.kt
lib/src/main/kotlin/starknet/provider/rpc/JsonRpcProvider.kt
lib/src/main/kotlin/starknet/provider/rpc/JsonRpcResponse.kt
lib/src/main/kotlin/starknet/service/http/HttpService.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt
lib/src/test/kotlin/starknet/utils/DevnetClient.kt
lib/src/test/resources/compileContracts.sh
lib/src/test/resources/compiled/providerTestAbi.json

Add transaction related methods

---

lib/src/test/kotlin/starknet/provider/ProviderTest.kt
lib/src/test/kotlin/starknet/utils/DevnetClient.kt

This PR restores one test and makes minor improvements to the rest.

Minor tests improvements

---

requirements.txt

Bump starknet-devnet to 0.2.8.

Bump devnet version

---

.github/workflows/build_and_publish_docs.yml

This PR resolves #60.
Some work needs to be done to make generated docs nicer (change the title, add copyright), but it's unrelated to the deployment itself.

Deploy docs on github pages

---

.github/workflows/build_and_publish_docs.yml

Do not store history on docs deployment

---

lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionReceipt.kt
lib/src/test/kotlin/starknet/provider/TransactionMappingTest.kt

Resolves #71 
Before merging, tests have to be added which requires mocking - #83 has to be merged first.

Map statuses not present in rpc to the rpc ones

---

lib/src/main/kotlin/com/swmansion/starknet/data/types/Event.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcMethod.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt

This PR closes #55. 
This PR was created under assumption that #83 will be merged in some form, so I'm creating is as a draft until that happens.

Add event endpoints

---

lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/Execution.kt

This PR simplifies Account interface and makes it more compatible with java (removed nullable and default parameters).
[x] This issue contains breaking changes

Improve account interface

---

.gitignore
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayGetBlockNumberSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayGetBlockTransactionCountSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/JsonRpcSyncPolymorphicSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/Execution.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/Responses.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcMethod.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
lib/src/main/kotlin/com/swmansion/starknet/service/http/HttpService.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt

Added gateway/rpc status endpoints
https://github.com/software-mansion/starknet-jvm/issues/57

Add status endpoints

---

lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/extensions/Request.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/Request.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt

This PR separates Account from Provider so that the Account interface becomes less bloated.
#96

Separate Account from Provider

---

lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt

This PR removes chainid parameter from Account constructor.

Remove chainid from account

---

lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt
lib/starknet-jvm.md

This PR adds example usages of the Account module to docs.

Add account docs

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

Add deps to pom

---

lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayCallContractTransformingSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayGetBlockNumberSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayGetBlockTransactionCountSerializer.kt

This PR makes all serializers `internal`.

Add missing internal to objects

---

lib/src/main/kotlin/com/swmansion/starknet/crypto/StarknetCurve.kt

Changes sign method of StarknetCurve from internal to public

Made sign method public

---

lib/src/main/kotlin/com/swmansion/starknet/deployercontract/Deployer.kt

This PR fixes AAR build after introduction of contractdeployer package.
Closes

Fix Deployer android build

---

javademo/src/main/java/com/example/javademo/Main.java

This PR extends the `javademo` adding some more "real life like" usages of the starknet-jvm library.
Closes #117

Extend javademo

---

lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt

Fixes second point from https://github.com/software-mansion/starknet-jvm/issues/156.

Add missing type to estimate fee

---

lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/GatewayRequestFailedException.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt
requirements.txt

This PR fixes incorrect serial names used for parsing gateway errors. 
Closes #155
- `code` removed from `GatewayRequestFailedException`.

Fix gateway errors

---

.github/workflows/build-and-publish.yml

Change paths of crypto-cpp libs in jar
Closes https://github.com/software-mansion/starknet-jvm/issues/162

Change paths for crypto-cpp libs

---

lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt

Closes https://github.com/software-mansion/starknet-jvm/issues/170

Fix GatewayProvider.getStorageAt

---

lib/build.gradle.kts

Closes https://github.com/software-mansion/starknet-jvm/issues/143

Automatically fetch dependencies in pom

---

lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt

This PR moves InvokeTransactionPayload to separate method to avoid duplication.
Closes #178

Move InvokeTransactionPayload serialization in GatewayProvider

---

lib/src/main/kotlin/com/swmansion/starknet/data/NetUrls.java
lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetChainId.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt

Add support for testnet2
Closes https://github.com/software-mansion/starknet-jvm/issues/204

Add support for testnet2

---

lib/src/main/kotlin/com/swmansion/starknet/data/serializers/JsonRpcTransactionPayloadPolymorphicSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/Payloads.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionPayload.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt

Change getEstimateFee interface, to accept any valid payload as TransactionPayload
Closes https://github.com/software-mansion/starknet-jvm/issues/224
- change of interface of `getEstimateFee`

Accept any payload in getEstimateFee

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts
lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
lib/src/test/kotlin/starknet/data/types/TransactionsTest.kt

Use different versioning for fee estimation

Use different versioning for fee estimation

---

lib/build.gradle.kts
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayTransactionTransformingSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt

Refactor transaction serialization in gateway

---

lib/starknet-jvm.md

This PR add basic documentation of the `Deployer` module with an example usage.
Closes

Document using `Deployer`

---

lib/src/main/kotlin/com/swmansion/starknet/data/TypedData.kt

This PR adds example usage to `TypedData` class documentation.
Closes

Typed data documentation

---

lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
lib/starknet-jvm.md

This PR replaces default arguments in Account interface with polymorphic methods. Default arguments don't translate nicely to java.
Closes
- Changes in Account interface

Replace `Account` interface default arguments

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts
lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayGetBlockTransactionCountSerializer.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/Event.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt
lib/src/test/kotlin/starknet/utils/DevnetClient.kt
lib/src/test/resources/src/providerTest.cairo
requirements.txt

Closes https://github.com/software-mansion/starknet-jvm/issues/102
Closes https://github.com/software-mansion/starknet-jvm/issues/206
Closes https://github.com/software-mansion/starknet-jvm/issues/232
Closes https://github.com/software-mansion/starknet-jvm/issues/215

Fix getEvents rpc endpoint, add more tests

---

.github/workflows/build-and-publish-docs.yml
.github/workflows/build-and-publish.yml
androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

This fixes a bug with wrong paths of native libs in jar archive

Fix paths to libs in jar file

---

lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/Execution.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt

Support for cairo1 account calldata
Closes #261

Support for cairo1 account calldata

---

lib/src/main/kotlin/com/swmansion/starknet/data/types/Responses.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt

Fix deserialization of getBlockWithTransactions response
Closes #265

Fix getBlockWithTransactions

---

.editorconfig
android/build.gradle
androiddemo/build.gradle.kts
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
lib/build.gradle.kts
lib/src/main/kotlin/com/swmansion/starknet/data/types/Contracts.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
requirements.txt

Reverts software-mansion/starknet-jvm#267

Revert "Bump deps"

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

Bump version to 0.6.2

---

README.md
lib/starknet-jvm.md

- Add Deploy Account example to readme and docs main page
- Highlight JsonRpc provider as preferred
Closes #286

[docs] Add deploy account contract example

---

README.md
lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/data/ContractAddressCalculator.kt
lib/src/main/kotlin/com/swmansion/starknet/data/NetUrls.java
lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/GatewayRequestFailedException.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/RequestFailedException.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/RpcRequestFailedException.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
lib/src/main/kotlin/com/swmansion/starknet/service/http/HttpService.kt
lib/src/main/kotlin/com/swmansion/starknet/signer/Signer.kt
lib/src/main/kotlin/com/swmansion/starknet/signer/StarkCurveSigner.kt

Convert StarkNet to Starknet

---

lib/build.gradle.kts
lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
lib/src/main/kotlin/com/swmansion/starknet/data/NetUrls.java
lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetChainId.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt
lib/src/test/resources/src_v0/providerTest.cairo
lib/starknet-jvm.md

- Removed testnet2 from enums
- Removed functions with `chainId` argument
- Removed tests for chain-specific testnet
Closes #309 
Closes #302 
- Removed ability to create chain-specific testnet providers

Remove Testnet2 support

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

* Add basic flow examples and corresponding tests by @DelevoXDG in https://github.com/software-mansion/starknet-jvm/pull/300
* Add support for getBlockWithTxHashes by @DelevoXDG in https://github.com/software-mansion/starknet-jvm/pull/305
* Update simulateTransactions to match RPC 0.4 by @DelevoXDG in https://github.com/software-mansion/starknet-jvm/pull/308
* Convert StarkNet to Starknet by @DelevoXDG in https://github.com/software-mansion/starknet-jvm/pull/306
* Remove Testnet2 support by @DelevoXDG in https://github.com/software-mansion/starknet-jvm/pull/312
* Support for Cairo 2 contracts by @DelevoXDG in https://github.com/software-mansion/starknet-jvm/pull/285

Bump version to 0.7.1

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

* https://github.com/software-mansion/starknet-jvm/pull/315
* https://github.com/software-mansion/starknet-jvm/pull/324
* https://github.com/software-mansion/starknet-jvm/pull/327

Bump version to 0.7.2

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

Bump version to 0.8.0

---

androiddemo/src/main/java/com/example/androiddemo/MainActivity.kt
javademo/src/main/java/com/example/javademo/Main.java

- Fix android demo
- Update java demo to use interfaces
Closes #377

Update demos to 0.9.0

---

.github/workflows/checks.yml

Fix Codecov upload

---

lib/build.gradle.kts

Starting with this PR, demos will be updated separately: #389

Bump version to 0.9.1

---

lib/build.gradle.kts
lib/src/main/kotlin/com/swmansion/starknet/data/types/Messages.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt

Add missing order field to OrderedMessageL2ToL1

---

.github/workflows/build-and-publish.yml

Allow version x.yz.w format in release workflow

---

lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
lib/src/main/kotlin/com/swmansion/starknet/data/TransactionHashCalculator.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetChainId.kt
lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
lib/src/test/kotlin/com/swmansion/starknet/data/TransactionHashCalculatorTest.kt
lib/src/test/kotlin/network/provider/ProviderTest.kt
lib/src/test/kotlin/starknet/data/types/TransactionsTest.kt
lib/src/test/kotlin/starknet/provider/ProviderTest.kt

This reverts commit cefe45cd0b74555c9594b67320ff3d02e9ebba12.
Closes
Undoes breaking changes from #415

Revert "Use Felt instead of StarknetChainId (#406)"

---

lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetChainId.kt

Update `StarknetChainId` docs

---

lib/build.gradle.kts

Bump version to 0.10.1

---

lib/src/test/kotlin/network/account/AccountTest.kt
lib/src/test/kotlin/network/provider/ProviderTest.kt
lib/src/test/kotlin/starknet/account/StandardAccountTest.kt

Fix tx version network tests
Closes

Fix `TransactionVersion` test cases

---

lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetByteArray.kt

Add StarknetByteArray docs

---

lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
lib/src/test/kotlin/starknet/data/TypedDataTest.kt

Groups related test cases in `@Nested` inner classes
Related to #428 
Closes

Nest TypedData-related test cases

---

lib/build.gradle.kts

Bump version to 0.11.1

---

androiddemo/build.gradle.kts
androiddemo/src/main/java/com/example/androiddemo/MainActivity.kt
javademo/build.gradle.kts
javademo/src/main/java/com/example/javademo/Main.java

- Bump demos to 0.11.1
- Use Cairo 1 accounts in demos for them to work with latest devnet
- Use v3 transactions in demos
Closes #389

Bump demos to 0.11.1

---

.github/workflows/checks.yml

- Update `Cmake` version from `3.16.x` to `3.18.1`
Closes #459

Update Cmake version to 3.18.1

---

lib/build.gradle.kts

Bump version to `0.12.1`

---

androiddemo/build.gradle.kts
androiddemo/src/main/java/com/example/androiddemo/MainActivity.kt
javademo/build.gradle.kts
javademo/src/main/java/com/example/javademo/Main.java

- Update example apps to version `0.12.1`
- Add batching examples in `javademo` 
Closes #476

Update examples to version `0.12.1`

---

.github/workflows/checks.yml

- Bump [cache action](https://github.com/marketplace/actions/cache) from v3 to v4
Closes #511

Bump cache action from v3 to v4

---

README.md

- Add command for updating submodules
- Add `Java` and `Cmake` prerequisites
- Add `Release checklist` section
Closes #503

Extend development section

---

lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetByteArray.kt
lib/src/test/kotlin/com/swmansion/starknet/data/types/ByteArrayTests.kt

Add `StarknetByteArray.toString()` method which parses byt array into its input.
Closes #515

Add `StarknetByteArray.toString`

---

lib/guide.md
lib/java-guide.md

Update java guide with changes which will be introduced in version `0.13.0`
Closes #523

Update guide to `0.13.0`

---

androiddemo/build.gradle.kts
androiddemo/src/main/java/com/example/androiddemo/MainActivity.kt
javademo/build.gradle.kts
javademo/src/main/java/com/example/javademo/Main.java

Update demo apps to version `0.13.0`
Closes #521

Bump demo apps to `0.13.0`

---

lib/build.gradle.kts

Bump version to `0.13.1`

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
lib/build.gradle.kts

Bump version to `0.13.1` in demo apps

---

androiddemo/build.gradle.kts
javademo/build.gradle.kts
javademo/src/main/java/com/example/javademo/Main.java
lib/build.gradle.kts

Bump demos to `0.14.0`

---

lib/src/main/kotlin/com/swmansion/starknet/data/serializers/ExecutableTransactionSerializer.kt

Remove invalid cases in `ExecutableTransactionSerializer.serialize()`
Closes

Update `serialize` method in `ExecutableTransactionSerializer`

---

.github/workflows/build-and-publish.yml

Use `actions/download-artifact@v4`

---

.github/workflows/build-and-publish.yml
.github/workflows/checks.yml

Bump ubuntu image to latest

---

lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
lib/src/test/kotlin/starknet/deployercontract/StandardDeployerTest.kt

Auto estimation on devnet has been fixed, so we can uncomment these tests
Closes #536

Remove todos

---

lib/build.gradle.kts

Bump version to 0.15.0

---

.github/workflows/build-and-publish.yml

Add cmake setup to `publish` job
Closes

Add cmake setup to `publish` job

---

gradle/wrapper/gradle-wrapper.properties
lib/build.gradle.kts

Downgrade gradle to `7.6.2`

---

build.gradle.kts

Bump version to 0.16.1
