- crypto/CMakeLists.txt
Adds Java and JNI as required for make build. 
Resolves errors with `jni.h` missing when building.
`JAVA_HOME` env var is still required for the build to be successful.
> Add Java and JNI as cmake requirements

- lib/src/main/kotlin/starknet/extensions/json.kt
- lib/src/main/kotlin/starknet/provider/rpc/JsonRpcProvider.kt
Starknet-devnet merged our fix to the RPC endpoint so temporary fixes introduced in starknet-jvm need to be reverted.
> Fix rpc declare and deploy after devnet update

- lib/src/main/kotlin/com/swmansion/starknet/data/types/Transactions.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
This PR closes #59. There are some tests that remain commented out or disabled for the rpc client because of the devnet limitations. For these more descriptive comments has been added.
Tests that weren't restored subject methods that are not implemented at all and I think should be left for post the initial release.
> Restore some of the disabled tests

- lib/src/main/kotlin/com/swmansion/starknet/data/NetUrls.java
- lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/GatewayRequestFailedException.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/RequestFailedException.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/exceptions/RpcRequestFailedException.kt
- lib/src/main/kotlin/com/swmansion/starknet/service/http/HttpService.kt
- lib/starknet-jvm.md
Resolves #94 and improves documentation of already existing public objects.
Also, it turns out you can document specific packages by adding `# Package full.path.to.package` sections to `starknet-jvm.md` file so in the future we can consider adding some code examples and more more details to specific sections. Currently, I've just included basic descriptions there.
> Add missing docs, improve existing

- .github/workflows/checks.yml
- lib/src/main/kotlin/com/swmansion/starknet/data/serializers/GatewayCallContractTransformingSerializer.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
- lib/src/test/kotlin/starknet/utils/DevnetClient.kt
- requirements.txt
This PR bumps devnet to 0.3.0 (temporarily from github branch) and updates related tests.
This PR also simplifies return type of `Provider.callContract`.
n/a
Return type of `Provider.callContract` changed.
> Bump devnet to 0.3.0 and update tests

- .github/workflows/checks.yml
This PR makes tests run both on `macos-latest` and `ubuntu-latest`. It does not address the issue of testing the package on Windows as this would require more complex refactors.
#105 
[ ] This issue contains breaking changes
> Run tests on linux

- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/utils/DevnetClient.kt
Some gunicorn processes (possibly worker) sometimes do not exit when main process is being interrupted, and their processes are left dangling which in turn fails our tests. This is a workaround for the problem.
https://github.com/software-mansion/starknet-jvm/issues/95
> Kill zombie devnet processes

- .github/workflows/build-and-publish-docs.yml
- androiddemo/build.gradle.kts
- javademo/build.gradle.kts
- lib/build.gradle.kts
- lib/starknet-jvm.md
This is a workaround for a problem with missing extensive descriptions on java docs.
https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#Descriptions
Closes https://github.com/software-mansion/starknet-jvm/issues/138
> Fix breaking whitespaces in java docs

- lib/src/main/kotlin/com/swmansion/starknet/service/http/OkHttpService.kt
> Stop creating new OkHttpClient for every async request

- javademo/src/main/java/com/example/javademo/Main.java
This PR replaces `Random` with `ThreadLocalRandom` because as it turns out, `Random.nextLong(loweBound, upperBound)` is not available in java 11.
Closes
> Use java 11 compatible code in javademo

- lib/src/main/kotlin/com/swmansion/starknet/service/http/HttpRequest.kt
Currently `thenApply` causes `deserialize` to run synchronously after future is resolved in OkHttp thread.
> Fix running synchronous action on Future coming from OkHttp

- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
This PR adds L1HandlerTransaction dataclass as well as suport for parsing these transactions to GatewayProvider.
It also inlines `transactionTypeToName` function.
Tests have been mocked until we resolve how to test L1<>L2 messaging with devnet (this is also being investigated by starknet.py team).
This PR however doesn't add support for L1HandlerTransactions to JsonRpcProvider as it is blocked by #146 
Closes #167
> Add `L1_HANDLER` transaction support for GatewayProvider

- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionReceipt.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
> Make actualFee nullable in GatewayProvider

- lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/TransactionHashCalculator.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Contracts.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionPayload.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
This PR adds support for signing declare transactions and sending them.
Closes #145
> Support signed declare transaction

- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionPayload.kt
- lib/src/test/kotlin/starknet/data/types/TransactionsTest.kt
This PR removes support for making InvokeTransactionPayloads and InvokeTransactions through TransactionFactory with version != 1. 
Version parameter is still exposed in InvokeTransaction data class for the use in serialization.
Closes #147 
Invoke transactions with version 0
> Remove support for making invoke transactions with version 0

- lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionPayload.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
This PR changes Provider interface so that `getEstimateFee` accepts `InvokeTransactionPayload` instead of `InvokeTransaction`.
Closes #174 
* Changes to the Provider interface
> Make `getEstimateFee` accept `InvokeTransactionPayload`

- lib/src/main/kotlin/com/swmansion/starknet/data/types/Execution.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Felt.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Uint256.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/conversions/ConvertibleToCalldata.kt
- lib/src/test/kotlin/com/swmansion/starknet/data/CallTest.kt
- lib/src/test/kotlin/com/swmansion/starknet/data/Uint256Test.kt
This PR introduces `ConvertibleToFeltList` interface to indicate that an object can be converted to list of Felts, e.g. to be used as Calldata.
It makes Uint256 implement ConvertibleToFeltList.
It makes StarkCurveSignature implement ConvertibleToFeltList.
It also does some cleanup of Uint256 class and introduces Uint256 tests.
Closes #188 
* StarkCurveSignature `toList()` method replaced with `toFeltList()`.
> `ConvertibleToFeltList` interface

- javademo/src/main/java/com/example/javademo/Main.java
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Execution.kt
This PR improves doc comments in `Call` class and extends javademo to show usages of `Call.fromCallArguments`.
This PR also introduces a bit of cleanup and reformatting in javademo.
Closes #201
> Add docs about `ConvertibleToCalldata`

- .github/workflows/build-and-publish.yml
Actions fail to build because of recent ubuntu version bump https://github.com/software-mansion/starknet-jvm/actions/runs/3648453295/jobs/6162840367
This rolls back the change and fixes system version.
This is a workaround.
Closes
> Rollback ubuntu version for x64 builds

- .github/workflows/Dockerfile.multiarch
- .github/workflows/build-and-publish-docs.yml
- .github/workflows/build-and-publish.yml
- .github/workflows/checks.yml
This PR adds support for older glibc (3.4.24) for arm architecture + updates gh actions to use newest versions without deprecation warnings. 
It also fixes ubuntu runner version to 20.04, as this is the newest version that easily supports g++-7; It still has ~3 years of support so we should be good. After amazon updates their Linux distros to use newer glibc versions we should think about also updating our runners and dropping older glibc.
Closes https://github.com/software-mansion/starknet-jvm/issues/189
Closes https://github.com/software-mansion/starknet-jvm/issues/171
> Support for older glibc for arm + update actions

- lib/src/main/kotlin/com/swmansion/starknet/crypto/StarknetCurve.kt
- lib/src/test/kotlin/starknet/crypto/StarknetCurveTest.kt
Added check in StarknetCurve.getPublicKey that fails if privateKey value is wrong, so exception is thrown from sdk rather than crypto-cpp.
Closes https://github.com/software-mansion/starknet-jvm/issues/216
> Throw an exception when illegal argument is passed in StarkCurve.getPublicKey

- .github/workflows/checks.yml
- .gitignore
- lib/build.gradle.kts
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/deployercontract/StandardDeployerTest.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
- lib/src/test/kotlin/starknet/utils/DevnetClient.kt
- lib/src/test/resources/junit-platform.properties
This PR configures most tests modules to run in parallel. 
StandardAccount and StandardDeployer still run in single thread, because parallel execution caused the tests to fail because of the invalid nonces.
Closes #228
> Enable parallel test execution

- lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/main/kotlin/com/swmansion/starknet/signer/Signer.kt
- lib/src/main/kotlin/com/swmansion/starknet/signer/StarkCurveSigner.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/starknet-jvm.md
This PR adds support for signing TypedData both in `Account` and `Signer` interfaces
Closes
* Account interface added `signTypedData` and `verifyTypedDataSignature`
* Signer interface added `signTypedData`
> Support signing TypedData

- androiddemo/build.gradle.kts
- javademo/build.gradle.kts
- lib/build.gradle.kts
- lib/src/main/kotlin/com/swmansion/starknet/provider/gateway/GatewayProvider.kt
Use `blockNumber` as key in getClassHashAt for blockTag in gateway
Closes https://github.com/software-mansion/starknet-jvm/issues/241
> Use blockNumber to get block per tag in gateway

- .gitmodules
- requirements.txt
Changed URL to `crypto-cpp` repository to a new one since the old one doesn't exist anymore.
Temporarily added `typeguard` and `Web3` to `requirements.txt` until PR is merged in `cairo-lang`
> Change url to new repository

- androiddemo/build.gradle.kts
- javademo/build.gradle.kts
- lib/build.gradle.kts
- lib/src/main/kotlin/com/swmansion/starknet/data/TypedData.kt
Return Felt.ZERO when value of field is null
Convert string to BigInteger instead of Long
Closes https://github.com/software-mansion/starknet-jvm/issues/251
> Fix TypedData parsing for null values and BigIntegers

- lib/src/main/kotlin/com/swmansion/starknet/data/serializers/JsonRpcTransactionTracePolymorphicSerializer.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Event.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Payloads.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/SimulatedTransaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- requirements.txt
Adds method and dataclasses for simulating transactions.
Closes #257
> Add method for simulateTransactions

- lib/src/main/kotlin/com/swmansion/starknet/data/serializers/JsonRpcTransactionTracePolymorphicSerializer.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/SimulatedTransaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionPayload.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
- lib/src/test/kotlin/integration/account/AccountTest.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- requirements.txt
Closes #307 
Not compatible with `starknet_simulateTransaction` (RPC 0.3)
> Update simulateTransactions to match RPC 0.4

- lib/src/main/kotlin/com/swmansion/starknet/data/serializers/JsonRpcTransactionTracePolymorphicSerializer.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/SimulatedTransaction.kt
- lib/src/test/kotlin/integration/account/AccountTest.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
Closes #323 
Closes #314 
- `InvokeTransactionTrace` is renamed to `InvokeTransactionTraceBase` with derived `RevertedInvokeTransactionTrace` and `InvokeTransactionTrace`.
- `InvokeTransactionTraceBase` currently  not have `executeInvocation` anymore.
- Instead, `InvokeTransactionTrace` has `executeInvocation` of type `FunctionInvocation`
- And `RevertedInvokeTransactionTrace` has `executeInvocation` of type `RevertedFunctionInvocation`
> Adjust `simulateTransactions` (#323, #314)

- lib/src/main/kotlin/com/swmansion/starknet/account/Account.kt
- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
-  Fix `estimateFee`:  Always use `PENDING` block tag in `estimateFee(List<Call>)`
- Add `estimateFee` methods with `BlockTag` param
- Add `getNonce` method with `BlockTag` param
Closes #322
> Account: Fix estimateFee; Add estimateFee and getNonce with BlockTag param

- androiddemo/build.gradle.kts
- javademo/build.gradle.kts
- lib/build.gradle.kts
Bump https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8 to the latest avaliable version. `1.7.1` seems like a typo from `1.7.10` that slipped unnoticed because deps in `lib` are ignored by javademo. 
Closes #354
> Bump kotlin-stdlib-jdk8 to 1.9.20; Bump version to 0.8.1

- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/TransactionHashCalculator.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/serializers/TransactionPayloadSerializer.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/Transaction.kt
- lib/src/main/kotlin/com/swmansion/starknet/data/types/transactions/TransactionPayload.kt
- lib/src/test/kotlin/com/swmansion/starknet/data/TransactionHashCalculatorTest.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/data/types/TransactionsTest.kt
Related to #409
- Add `TransactionVersion` enum
- Use it instead of `Felt` in tx, tx payload dataclasses and related functions
Closes #412 
- `version` argument in `TransactionFactory` functions is now of type `TransactionVersion` instead of `Felt`
- `version` argument in `TransactionHashCalculator` functions is now of type `TransactionVersion` instead of `Felt`
- `TransactionPayload.version` is now of type `TransactionVersion` instead of `Felt`
> Add `TransactionVersion` enum

- lib/src/main/kotlin/com/swmansion/starknet/data/types/Payloads.kt
Closes #429 
- Payload classes from `com.swmansion.starknet.data.types.Payloads` are no longer accessible
> Make `Payloads.kt` classes internal

- lib/src/main/kotlin/com/swmansion/starknet/data/types/Felt.kt
- lib/src/test/kotlin/com/swmansion/starknet/data/types/NumAsHexBaseTests.kt
Related to and is needed for #428 
- Add support for creating `Felt` from signed value (`BigInteger`, `Long`, `Int`)
Closes
> Add `Felt.fromSigned` factory method

- lib/src/main/kotlin/com/swmansion/starknet/data/types/StarknetByteArray.kt
- lib/src/main/kotlin/com/swmansion/starknet/extensions/SplitToShortStrings.kt
- lib/src/test/kotlin/com/swmansion/starknet/data/types/ByteArrayTests.kt
Related to and is needed for #428 
- Add `StarknetTypedData` that corresponds to `ByteArray` struct in Cairo
Closes
- [Serialization of byte arrays](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/serialization_of_Cairo_types/#serialization_of_byte_arrays)
- Tests in [cairo repo](https://github.com/starkware-libs/cairo/blob/b22e43ffecf884877ed3a65d3077c0b8af586d6c/corelib/src/test/byte_array_test.cairo#L458)
> Add ByteArray

- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
As [https://github.com/0xSpaceShard/starknet-devnet-rs/issues/248](https://github.com/0xSpaceShard/starknet-devnet-rs/issues/248) is resolved, we can re-enable declare devnet tests
Closes #364
> Re-enable declare devnet tests

- .github/workflows/build-and-publish.yml
- Update `Cmake` version from `3.16.x` to `3.18.1` in build and publish workflow
Closes
> Update cmake to `3.18.1` in build and publish workflow

- lib/src/main/kotlin/com/swmansion/starknet/data/TypedData.kt
- lib/src/test/kotlin/starknet/data/TypedDataTest.kt
- Change `TypedData.encodeValue(...): Pair<String, Felt>` to `TypedData.encodeValue(...): Felt`
Closes #450
> Return only hash in `TypeData.encodeValue()`

- .github/workflows/build-and-publish.yml
- lib/src/main/kotlin/com/swmansion/starknet/provider/Provider.kt
- lib/src/main/kotlin/com/swmansion/starknet/provider/rpc/JsonRpcProvider.kt
- lib/src/test/kotlin/starknet/provider/ProviderTest.kt
- Add `Provider.getStorageAt()` accepting `key` param as `String`
- Add `JsonRpcProvider.getStorageAt()` implementations
- Add `get storage at with key as string` test in `ProviderTest`
Closes #333
> Accept key as string in `Provider.getStorageAt()`

- lib/src/main/kotlin/com/swmansion/starknet/data/TypedData.kt
Fix `TypedData.toJsonString()` by adding `encodeDefaults` flag set to `true`.
Before: `type` field has been skipped while serializing `MerkleTreeType` and `EnumType`, because their value is default
After: `type` field is properly serialized
Closes #498
> Fix `TypedData.toJsonString()`

- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/test/kotlin/network/account/AccountTest.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/src/test/kotlin/starknet/utils/DevnetClient.kt
- Restore `StandardAccount` constructor with `cairoVersion` param
- Change default `cairoVersion` to `CairoVersion.ONE`
- Introduce static method `StandardAccount.create()`, which allows to create a `StandardAccount` instance with automatic determination of Cairo version
Closes
> Add `StandardAccount.create()`

- lib/src/main/kotlin/com/swmansion/starknet/account/StandardAccount.kt
- lib/src/test/kotlin/starknet/account/StandardAccountTest.kt
- lib/starknet-jvm.md
Allow users to generate random private key.
- Add static method `StandardAccount.generatePrivateKey()` used to generated random private key
Closes #506
> Add `StandardAccount.generatePrivateKey()`

- lib/src/main/kotlin/com/swmansion/starknet/data/types/Event.kt
Allow nullable fields in `GetEventsPayload` (apart of `chunkSize` which is required, [spec ref](https://github.com/starkware-libs/starknet-specs/blob/6d88b7399f56260ece3821c71f9ce53ec55f830b/api/starknet_api_openrpc.json#L789)).
Closes #525
> Allow nullable fields `GetEventsPayload`

- lib/src/main/kotlin/com/swmansion/starknet/data/types/Event.kt
Change `continuationToken` default value to `null` in accordance with spec.
Closes
-  `continuationToken` field in `GetEventsPayload` and `GetEventsResult` has default value `null` instead of `"0"`
> Change `continuationToken` default value to `null`

- crypto/pedersen/CMakeLists.txt
Build workflow failed (example [here](https://github.com/software-mansion/starknet-jvm/actions/runs/14214865048/job/39829144456)), because the old url for boost library download was expired. Updated [it](https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz) to an [available one](https://archives.boost.io/release/1.79.0/source/boost_1_79_0.tar.gz).
Closes
> Update boost lib download url

- .github/workflows/build-and-publish-docs.yml
Docs workflow failed (check [this CI run](https://github.com/software-mansion/starknet-jvm/actions/runs/14222779700/job/39856062299)) because cmake was missing - this PR adds it.
Closes
> Add cmake setup to docs workflow

- .github/workflows/checks.yml
- lib/src/main/kotlin/com/swmansion/starknet/data/types/Responses.kt
- lib/src/test/kotlin/starknet/crypto/FeeUtilsTest.kt
- lib/src/test/kotlin/starknet/provider/response/JsonRpcResponseTest.kt
Support RPC 0.8.1
Closes
`EstimateFeeResponse`:
- gas amount fields are now of type `Uint64`
- gas price fields are now of type `Uint128`
- `overallFee` fields is now of type `Uint128`
> Support RPC 0.8.1

- .github/workflows/build-and-publish.yml
The issue arised because we tried to move files matched by strict pattern (`lib-[0-9].[0-9][0-9].[0-9].jar`, similarly for javadoc and source JARS), which resulted in crash when creating rc version.
Closes
> Update pattern when moving *.jar files

- .github/workflows/build-and-publish.yml
- gradle/wrapper/gradle-wrapper.properties
- lib/build.gradle.kts
Since the end of June 2025, OSSRH service is not working anymore, hence the need to adjust publishing plugin.
For more, please read https://central.sonatype.org/pages/ossrh-eol/
I've chosen https://github.com/vanniktech/gradle-maven-publish-plugin because it was recommended on official gradle website https://cookbook.gradle.org/integrations/maven-central/publishing/#plugins-for-publishing-to-maven-central
Closes
> Fix publishing to maven

- lib/build.gradle.kts
In 0.27.0 of maven publish plugin, [default Sonatype host](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/0139cc82597460126ed81b8b33e4ba7960c55db2/plugin/src/main/kotlin/com/vanniktech/maven/publish/SonatypeHost.kt#L27) used old OSSRH, this PR uses s01.
Closes
> Use `SonatypeHost.S01` for `publishToMavenCentral`
